### ISSUE TITLE
time slot is too short.

### ISSUE THREAD

**Issue by kevinwenyu** [notmarek/LanguageBreak#2]
time slot is very very short. any better way to speed up?

**Comment by notmarek** [comment]
Nothing i can do.

**Comment by fonix232** [comment]
For future reference - if you're struggling with plugging in the microUSB in time on step 10, I'd recommend using a magnetic adapter _only for this use_. I can't recommend using them for everyday charging/data transfer due to well documented issues with arcing/shorting/overheating, but for this short term usage, it should be fine.
