### ISSUE TITLE
issues with steps 10-12

### ISSUE THREAD

**Issue by benswolo** [notmarek/LanguageBreak#31]
I used release 1.0.2.1 to install the firmware on my kindle paperwhite 5th gen (11th) after update software to 5.16.2.1.1. I was able to successfully get the splash page ("it was the chinese all along"), but installing the language hotfix .bin failed. I tried following all the steps again but every time I drag languagebreak folder for the device for the second time (after "reselling device"), the device automatically kicks itself off my computer and reboots in normal mode, not demo mode. I'm pretty sure I'm dragging the files onto the kindle before it kicks me off, but I'm not sure if the jailbreak was successful, but I don't see a mkk folder. 

Any help would be appreciated.

**Comment by mr-deamon** [comment]
That sounds similar to my issue #34 . Do you have an error after resell?

**Comment by aubreynngomah-bit** [comment]
**Symptom:** PW3, firmware 5.16.2.1.1. After the Resell → "Press Power Button" → language-select (Chinese) sequence, the device repeatedly fell back into demo mode / Wi-Fi+registration setup instead of showing the jailbreak log message. `;log` behaved as a literal search (0 results), and no `mkk` folder was present. This happened **6 times in a row**, which let us rule out some common suspects:

- **Missed timing window** — verified via an automated disk-level polling script (PowerShell, polling `Get-Disk` every ~50ms rather than waiting on a drive-letter mount). The LanguageBreak folder copy to the exposed storage completed in ~100ms–1.1s after the drive first appeared, well within any reasonable window, and robocopy confirmed the write actually landed (not skipped due to a stale/failed write).
- **Unsafe unplug** — verified proper Windows "Safely Remove Hardware"/eject (via the Shell COM `InvokeVerb("Eject")` API) was used before every physical disconnect, every attempt.
- Also tried excluding `.demo` from the second (post-Resell) copy per a workaround mentioned elsewhere in this thread/MobileRead — made no difference for us either way.

**What finally worked:** attempt **#7**, with no procedural change from attempts 5–6 other than plugging the USB cable back in *immediately* upon confirming "Resell" rather than waiting to visually read the "Press Power Button" prompt first (removing a human reaction-time step). That said, the copy on the successful attempt was actually *skipped* (files already matching, i.e. the storage hadn't been wiped before that window) rather than a fresh write — so we can't conclusively say faster replugging was the deciding factor rather than this exploit just being somewhat nondeterministic for this device+firmware combo. Posting in case the "verified fast, verified real copy, still fails" data point helps narrow down the actual cause, or saves someone else from assuming they're doing something wrong when persistence is what it actually takes.

Full jailbreak succeeded after this: `languagebreak_log` on-device shows `Finished installing jailbreak!`, hotfix applied cleanly, `mkk`/`libkh`/`rp` present, device stable through reboot.
