### ISSUE TITLE
PW3, 5.16.2.1.1, strange state, how to redo JB?

### ISSUE THREAD

**Issue by mr-deamon** [notmarek/LanguageBreak#34]
Hi
I attempted to JB my Kindle. The first attempt did not go all the way according to the manual. Still it displayed some lines of text while booting _once_.

I copied the hotfix (EN_US) and it did not complain when i told it to install. But if i now enter ;log, it does not "confirm" the JB. Nor are there any folders in the filesystem.

Now i tried over and over again. But i cannot redo the JB. After step 3 it "crashes" (Collecting debug info). Then i can do the rest, but after step 12, i don't get a language-selection anymore...

What state is my kindle in? Any chance for still having a proper Jailbreak?
Thank you so much!
Chris

**Comment by hunterzero99** [comment]
I'd try reinstalling the 5.16.2.1.1 update then starting over at the beginning.

**Comment by mr-deamon** [comment]
Hi
I tried that. It worked - at least it did not complain. But the "Collecting debug info" still appears after step 3. I just found [this](https://www.mobileread.com/forums/showpost.php?p=4391901&postcount=733). So i'll give it another try or multiple... maybe it'll work on one of the next tries?!

**Comment by mr-deamon** [comment]
Okay, i was able to resolve this myself after hours of trying... Solution was: Do as @hunterzero99 told, re-install 5.16.2.1.1. BUT: I had to reinstall twice:
1. Reinstall
2. Reset Kindle
3. Reinstall again
4. Do the instructions of the JB.

Still strange: There was no Pseudot-entry in the language-selection. It still works, KUAL is now installed.
Thank you so much!

**Comment by aubreynngomah-bit** [comment]
**Symptom:** PW3, firmware 5.16.2.1.1. After the Resell → "Press Power Button" → language-select (Chinese) sequence, the device repeatedly fell back into demo mode / Wi-Fi+registration setup instead of showing the jailbreak log message. `;log` behaved as a literal search (0 results), and no `mkk` folder was present. This happened **6 times in a row**, which let us rule out some common suspects:

- **Missed timing window** — verified via an automated disk-level polling script (PowerShell, polling `Get-Disk` every ~50ms rather than waiting on a drive-letter mount). The LanguageBreak folder copy to the exposed storage completed in ~100ms–1.1s after the drive first appeared, well within any reasonable window, and robocopy confirmed the write actually landed (not skipped due to a stale/failed write).
- **Unsafe unplug** — verified proper Windows "Safely Remove Hardware"/eject (via the Shell COM `InvokeVerb("Eject")` API) was used before every physical disconnect, every attempt.
- Also tried excluding `.demo` from the second (post-Resell) copy per a workaround mentioned elsewhere in this thread/MobileRead — made no difference for us either way.

**What finally worked:** attempt **#7**, with no procedural change from attempts 5–6 other than plugging the USB cable back in *immediately* upon confirming "Resell" rather than waiting to visually read the "Press Power Button" prompt first (removing a human reaction-time step). That said, the copy on the successful attempt was actually *skipped* (files already matching, i.e. the storage hadn't been wiped before that window) rather than a fresh write — so we can't conclusively say faster replugging was the deciding factor rather than this exploit just being somewhat nondeterministic for this device+firmware combo. Posting in case the "verified fast, verified real copy, still fails" data point helps narrow down the actual cause, or saves someone else from assuming they're doing something wrong when persistence is what it actually takes.

Full jailbreak succeeded after this: `languagebreak_log` on-device shows `Finished installing jailbreak!`, hotfix applied cleanly, `mkk`/`libkh`/`rp` present, device stable through reboot.
